# Generated by Django 3.0.4 on 2020-03-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=50)),
                ('mail_id', models.CharField(max_length=40)),
                ('duration', models.IntegerField(null=True)),
                ('joining_date', models.DateField(null=True)),
                ('paid_amount', models.IntegerField(null=True)),
                ('balance_amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PHONE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_number', models.CharField(max_length=30)),
                ('ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.STUDENT')),
            ],
        ),
        migrations.CreateModel(
            name='COURSES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=40)),
                ('member', models.ManyToManyField(to='sis.STUDENT')),
            ],
        ),
    ]
